### ISSUE TITLE
Segment name and icon is not even implemented in the detailed timer.

### ISSUE THREAD

**Issue by TheEssenceOfDarkness** [CryZe/LiveSplitOne#52] opened 2017-10-30 16:01 UTC
Checking the box to enable them does absolutely nothing as the componment itself does not even have code written to display them.

**Comment by CryZe** [comment] 2017-10-30 17:07
Dupl

**Comment by CryZe** [comment] 2017-10-30 17:07
Duplicate of #37

**Closed by CryZe** 2017-10-30 17:07 UTC
